config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root to: "homes#top"
  get "home/about", to: "homes#about"
  get "home/top", to: "homes#top"


  resources :books, only: [:index, :show, :edit, :create, :destroy, :update, :new] do
    resources :comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  # 1対多のDM
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    # ↓非同期の検索
    get "search" => "users#search"
  end

  # グループDM
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # フォローフォロワー
    # ネストさせる
    resources :users do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  attr_accessor :rate

  # ↓本の投稿数を数えるので、book.rbに記述してく。
  # scope :スコープの名前, -> { 条件式 }
  # モデル側であらかじめ特定の条件式に対して名前をつけて定義し、
  # その名前でメソッドの様に条件式を呼び出すことが出来る仕組みのこと!!
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 

  # ↓これで1週間の投稿数のグラフができる
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  # １対多のDM
  validates :content, presence: true, length: { maximum:140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    # class_name: "User"でUserモデルを参照
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :entries, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 20 }, uniqueness: true

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy

  # 1対多のDM
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  def following?(user)
    followings.include?(user)
  end


  # フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
# 一覧画面で使う
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower

# フォローしたときの処理
def follow(user_id)
  relationships.create(followed_id: user_id)
end
# フォローを外すときの処理
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
# フォローしているか判定
def following?(user)
  followings.include?(user)
end


  
  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end

  
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(id: :desc)
    @book = Book.new
    @users = User.all
    
    #過去の投稿数カウントに使用 
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    # 1対多のDM
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu| 
        @userEntry.each do |u| 
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def search
    # これ一式で非同期検索できる
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  def index
    @users = User.all
    @book = Book.new
    
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash[:updated] = "Your account has error"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% unless current_user == user %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

    
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>


    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


    


      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <%= render 'relationships/follow_list', users: @users %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>

        </div>


        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>


        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>


        <div class="form-group">
          <%= f.submit class: 'btn btn-secondary' %>
        </div>


      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>

  
<div class='col-md-3'>

    <h2>User info</h2>
    <%= render 'info', user: current_user %>
    <%= render 'relationships/follow_list', users: @users %>

    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
</div>


<div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <%=link_to "グループを作成する",new_group_path %> | 
<%=link_to "グループ一覧",groups_path %>
    <%= render 'index', users: @users %>
    
</div>

  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>


      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <%= render 'relationships/follow_list', users: @users %>

      
      <% if @user != current_user %>
      <% if (current_user.following?(@user)) && (@user.following?(current_user)) %>
        <% if @isRoom == true %>
          <%= link_to "チャットへ",  room_path(@roomId), class: "btn btn-primary" %>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class: "btn btn-primary user-show-chat" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>



     <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
    <% end %>




      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
      
      


      <h3>投稿数の前日比・前週比</h3>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今日の投稿</th>
        <th>昨日の投稿</th>
        <th>前日比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @today_book.count %></td>
	  <td><%= @yesterday_book.count %></td>
        <% if @yesterday_book.count == 0 %>
	  <td>前日の投稿はなし</td>
        <% else %>
	  <td><% @the_day_before =   @today_book.count / @yesterday_book.count  %>
	  <%= (@the_day_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>
      
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>先週比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @this_week_book.count %></td>
	  <td><%= @last_week_book.count %></td>
        <% if @last_week_book.count == 0 %>
	  <td>先週の投稿はなし</td>
        <% else %>
	  <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
	  <%= (@the_week_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>
    <br>



    

    <h2>7日分の投稿数</h2>
    <table class="table table-bordered ">
      <tr>
        <th>今日</th>
        <th>1日前</th>
        <th>2日前</th>
        <th>3日前</th>
        <th>4日前</th>
        <th>5日前</th>
        <th>6日前</th>
      </tr>
      <tr>
        <td><%= @books.created_today.count %></td>
        <td><%= @books.created_yesterday.count %></td>
        <td><%= @books.created_2day_ago.count %></td>
        <td><%= @books.created_3day_ago.count %></td>
        <td><%= @books.created_4day_ago.count %></td>
        <td><%= @books.created_5day_ago.count %></td>
        <td><%= @books.created_6day_ago.count %></td>
      </tr>
    </table>
    <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6day_ago.count %>,
                <%= @books.created_5day_ago.count %>,
                <%= @books.created_4day_ago.count %>,
                <%= @books.created_3day_ago.count %>,
                <%= @books.created_2day_ago.count %>,
                <%= @books.created_yesterday.count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>





    </div>

    

  </div>
</div>